workflows:
  ios-diia-workflow:
    name: Diia iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "DiiaApp.xcodeproj"
        XCODE_SCHEME: "DiiaApp"
        BUNDLE_ID: "com.nutipov.diia"
      xcode: 15.0
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Build
        script: |
          set -e
          set -x
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "$HOME/build/DiiaApp.xcarchive" \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      
      - name: Create IPA
        script: |
          set -e
          set -x
          mkdir -p "$HOME/build/ipa"
          cd "$HOME/build"
          
          # Перевіряємо що Assets є в архіві
          echo "Checking for Assets in archive..."
          find DiiaApp.xcarchive -name "Assets.car" -o -name "AppIcon*"
          
          mkdir -p Payload
          cp -r DiiaApp.xcarchive/Products/Applications/DiiaApp.app Payload/
          
          # Перевіряємо що Assets скопіювались в .app
          echo "Checking Assets in .app bundle..."
          ls -la Payload/DiiaApp.app/ || true
          find Payload/DiiaApp.app -name "Assets.car" -o -name "AppIcon*" || true
          
          zip -r ipa/DiiaApp.ipa Payload
          rm -rf Payload
          ls -lh ipa/DiiaApp.ipa
    
    artifacts:
      - $HOME/build/ipa/*.ipa
      - $HOME/build/DiiaApp.xcarchive
    
    publishing:
      email:
        recipients:
          - nutipovottakvot@gmail.com
        notify:
          success: true
          failure: true
