workflows:
  ios-diia-workflow:
    name: Дія iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.nutipov.diia
      
      vars:
        XCODE_PROJECT: "DiiaApp.xcodeproj"
        XCODE_SCHEME: "DiiaApp"
        BUNDLE_ID: "com.nutipov.diia"
      
      xcode: 15.0
      cocoapods: default
    
    scripts:
      - name: Set Bundle ID
        script: |
          echo "Building with Bundle ID: $BUNDLE_ID"
          
      - name: Build iOS app
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $HOME/Library/Developer/Xcode/Archives/DiiaApp.xcarchive \
            clean archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      
      - name: Export IPA
        script: |
          xcodebuild \
            -archivePath $HOME/Library/Developer/Xcode/Archives/DiiaApp.xcarchive \
            -exportArchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      email:
        recipients:
          - nutipovottakvot@gmail.com
        notify:
          success: true
          failure: true

