workflows:
  ios-diia-workflow:
    name: Дія iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.yourteam.diia
      
      vars:
        XCODE_WORKSPACE: "DiiaApp.xcworkspace"
        XCODE_SCHEME: "DiiaApp"
        APP_ID: "com.yourteam.diia"
      
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Install dependencies
        script: |
          # Если используешь CocoaPods
          # pod install
          
      - name: Build iOS app
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $HOME/Library/Developer/Xcode/Archives/DiiaApp.xcarchive \
            archive
      
      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $HOME/Library/Developer/Xcode/Archives/DiiaApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ios/ipa
    
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      email:
        recipients:
          - nutipovottakvot@gmail.com
        notify:
          success: true
          failure: true

